branches:
  only:
    - master
env:
  - COVERALLS_PARALLEL=true
language: ruby
bundler_args: --binstubs
rvm:
  - 2.0.0
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - psql -c 'create database kinship_test' -U postgres
  - psql -c "CREATE USER kinship_test WITH CREATEDB PASSWORD 'kinship';" -U postgres
script:
  - bundle exec rake db:setup
  - bundle exec rspec
  - bundle exec cucumber
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=2QNUX8aQd6YAuAVYc6ZmmU1sXwT0u0GxC
