default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: kinship_development

test: &test
  <<: *default
  database: kinship_test

production:
  <<: *default
  database: kinship
